# Generated by Django 3.2 on 2021-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='highschool',
            field=models.CharField(choices=[('일반고', '일반고'), ('특목고', '특목고'), ('특성화고', '특성화고'), ('자공고, 자사고', '자공고, 자사고'), ('기타', '기타')], max_length=10),
        ),
    ]
