# Generated by Django 3.2 on 2021-06-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mentor_check',
            field=models.BooleanField(default=False),
        ),
    ]
