# Generated by Django 3.2 on 2021-07-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210701_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='complete_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gradepoint',
        ),
    ]
