# Generated by Django 3.2 on 2021-07-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210701_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
