# Generated by Django 3.2 on 2021-07-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
