# Generated by Django 3.2 on 2021-07-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='university',
            field=models.CharField(default='멘토만 작성', max_length=20),
        ),
    ]
