# Generated by Django 3.2.4 on 2021-06-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
