# Generated by Django 3.2 on 2021-07-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_muniver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Muniver',
        ),
    ]
