# Generated by Django 3.2 on 2021-06-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(default=3)),
                ('mentee_major', models.CharField(max_length=50)),
                ('mentee_entrancetype', models.CharField(max_length=50)),
                ('counsel', models.TextField()),
                ('creadted_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.CharField(max_length=15)),
                ('mentor', models.CharField(max_length=15)),
                ('mentee_highschool', models.CharField(choices=[('일반고', '일반고'), ('특목고', '특목고'), ('특성화고', '특성화고'), ('자공고, 자사고', '자공고, 자사고'), ('기타', '기타')], max_length=10)),
            ],
        ),
    ]
