# Generated by Django 3.2 on 2021-06-29 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteerequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee_request',
            name='grade',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
