# Generated by Django 3.2 on 2021-06-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteerequest', '0002_alter_mentee_request_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee_request',
            name='grade',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), ('기타', '기타')], max_length=2),
        ),
    ]
