# Generated by Django 3.2 on 2021-07-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteerequest', '0005_auto_20210630_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee_request',
            name='mentor_email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
