# Generated by Django 3.2 on 2021-07-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteerequest', '0007_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='point',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
