# Generated by Django 3.2 on 2021-07-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menteerequest', '0009_alter_point_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='count',
        ),
    ]
