# Generated by Django 3.2 on 2021-07-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteerequest', '0010_remove_point_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='grade',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]),
        ),
    ]
