# Generated by Django 3.2 on 2021-07-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteerequest', '0011_alter_point_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='grade',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=5),
        ),
    ]
