# Generated by Django 3.2 on 2021-07-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteerequest', '0012_alter_point_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee_request',
            name='finish_check',
            field=models.BooleanField(default=0),
        ),
    ]
