# Generated by Django 3.2 on 2021-07-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteerequest', '0013_mentee_request_finish_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='mname',
            name='post_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
